---
- name: Generate new RHEL custom ISO file
  hosts: bastion
  gather_facts: true
  become: true

  # need to add the logic to include an ssh key OR enable ssh passwordauthentication

  vars:
    my_flavor: rhel
    my_os_type: "{{ flavor[my_flavor].my_os_type }}"
    my_original_iso_full_filename: "{{ flavor[my_flavor].my_original_iso_full_filename }}"
    my_custom_iso: "{{ flavor[my_flavor].my_custom_iso }}"

    # Directories and files
    my_working_dir: /tmp/working-dir
    my_mnt_dir: /tmp/mnt-dir

    # General iso configuration
    my_system_language: "{{ flavor[my_flavor].my_system_language }}"
    my_keyboard_layout: "{{ flavor[my_flavor].my_keyboard_layout }}"
    my_time_zone: "{{ flavor[my_flavor].my_time_zone }}"
    my_root_pass: "{{ flavor[my_flavor].my_root_pass }}"

    # Networking options for iso file
    my_network_bootprotocol: dhcp # Mandatory variable, options are "dhcp" or "static"
    my_hostname: testhostname # Optional
    # my_netdevice: eht1 # Optional, only to be used if my_network_bootprotocol is "static"
    # my_ip: 192.168.1.23 # Mandatory when my_network_bootprotocol is "static"
    # my_netmask: 24 # Optional, only to be used if my_network_bootprotocol is "static"
    # my_gateway: 4.5.6.7 # Optional, only to be used if my_network_bootprotocol is "static"
    # my_dns_server: 8.8.8.8 # Optional, only to be used if my_network_bootprotocol is "static"

    # Optional Red Hat CDN user and password for registering with Insights
    my_rhn_user: "{{ rhsm_username }}"
    my_rhn_pass: "{{ rhsm_password }}"
    # passwords are in secrets.yml and need to be handed over at cmd-line with -e @secrets.yml
    # OR in AAP there is a credential type create rhsm and a credential rhsm whihc needs to be added to the job

    # Optional, users to be created. You can add as many users as you want by growing the dictionary with the same structure
    # Every entry on the dictionary must have "name" and "password" fields, optionally you can define additional groups for
    # the user with the "groups" field (see example below)
    my_users:
      - name: ansible
        password: redhat
        groups: wheel
      - name: preciado
        password: redhat
        groups: wheel
      - name: pablo
        password: redhat

  roles:
    - custom-iso-role
