---
- name: Generate new Windows custom ISO file
  hosts: bastion
  become: true
  gather_facts: true

  vars:
    # Directories and files
    my_original_iso_full_path: "/var/www/html/isos/windows2019.iso"
    my_custom_iso: "/var/www/html/isos/custom-windows2019.iso"
    my_working_dir: /tmp/working-dir
    my_mnt_dir: /tmp/mnt-dir
    my_os_type: "Windows"


  roles:
    - custom-iso-role
