---
- name: Generate new Windows custom ISO file
  hosts: bastion
  become: true
  gather_facts: true

  vars:
    # Directories and files
    my_original_iso_full_filename: "{{ win_flavor.my_original_iso_full_filename }}"
    my_custom_iso: "{{ win_flavor.my_custom_iso }}"
    my_os_type: "{{ win_flavor.my_os_type }}"

    my_working_dir: /tmp/working-dir
    my_mnt_dir: /tmp/mnt-dir

  roles:
    - custom-iso-role
