---
- name: Upload ISO files to DataStore
  hosts: bastion
  become: false

  vars:
    my_flavor: "win"
    my_source_file_full_filename: "{{ flavor[my_flavor].my_custom_iso }}"
    my_destination_filename: "{{ my_vcenter_isofile_dir }}/{{ flavor[my_flavor].my_custom_iso_short }}"

  tasks:

    - name: Copy file from host to DataStore
      community.vmware.vsphere_copy:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
        src: "{{ my_source_file_full_filename }}"
        datacenter: "{{ my_vcenter_datacenter_name }}"
        datastore: "{{ my_vcenter_datastore_name }}"
        path: "{{ my_destination_filename }}"
      delegate_to: bastion
