---
- name: Upload ISO files to DataStore
  hosts: bastion
  become: false

  vars:

    my_source_file_full_path: "/var/www/html/isos/custom-windows2019.iso"
    my_vcenter_datacenter_name: "bcl-cluster"
    my_datastore_name: "datastore1 (2)"
    my_destination_path: "custom-windows2019.iso"

  tasks:

    - name: Copy file from host to DataStore
      community.vmware.vsphere_copy:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        src: "{{ my_source_file_full_path }}"
        datacenter: "{{ my_vcenter_datacenter_name }}"
        datastore: "{{ my_datastore_name }}"
        path: "{{ my_destination_path }}"
      # delegate_to: bastion
