########################################################################
#
# The aim of this playbook is to create a VMware template out of an custom RHEL ISO image.
# We need to follow several steps before we can achieve that:
#   1. Boot a VM from a iso image in cdrom (that iso needs to be configured to run unattended installation, typically using kickstart)
#   2. Not implemented yet: install VMtools
#   2.a seal or sysprep the VM
#   3. Poweroff virtual machine (thoretically there is no need but it's safer and consume less CPU/memory when taking the snapshot)
#   4. Create template from virtual machine
#
########################################################################
---
- name: Playbook to create a VMware template from a custom iso image
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    my_flavor: "rhel"
    my_template_name: "{{ flavor[my_flavor].my_template_name }}"

    # Vars  related to the template

    my_template_cpu_count: "{{ flavor[my_flavor].my_template_cpu_count }}"
    my_template_memory_mib: "{{ flavor[my_flavor].my_template_memory_mib }}"
    my_template_disk_capacity_gb: "{{ flavor[my_flavor].my_template_disk_capacity_gb }}"

    my_iso_file_fullname: "{{ my_vcenter_isofile_dir_with_ds }}/{{ flavor[my_flavor].my_custom_iso_short }}"

  tasks:
    - name: Boot virtual machine from our custom ISO image in CDROM
      vmware.vmware_rest.vcenter_vm:
        placement:
          cluster: "{{ lookup('vmware.vmware_rest.cluster_moid', '/{{ my_vcenter_datacenter_name }}/host/{{ my_vcenter_cluster_name }}') }}"
          datastore: "{{ lookup('vmware.vmware_rest.datastore_moid', '/{{ my_vcenter_datacenter_name }}/datastore/{{ my_vcenter_datastore_name }}') }}"
          folder: "{{ lookup('vmware.vmware_rest.folder_moid', '/{{ my_vcenter_datacenter_name }}/vm/{{ my_vcenter_folder_name }}') }}"
        name: _temporary_rhelvm_do_not_delete
        guest_OS: RHEL_9_64
        power_on: true
        hardware_version: VMX_19
        cpu:
          count: "{{ my_template_cpu_count }}"
        memory:
          hot_add_enabled: true
          size_MiB: "{{ my_template_memory_mib }}"
        cdroms:
          - start_connected: true
            backing:
              iso_file: "{{ my_iso_file_fullname }}"
              type: ISO_FILE
              state: present
            type: SATA
            sata:
              bus: 0
              unit: 0
            state: connected
        disks:
          - type: SATA
            new_vmdk:
              capacity: '{{ my_template_disk_capacity_gb | human_to_bytes(default_unit="G") }}'
        nics:
          - start_connected: true
            backing:
              type: DISTRIBUTED_PORTGROUP # STANDARD_PORTGROUP
              network: "{{ lookup('vmware.vmware_rest.network_moid', '/{{ my_vcenter_datacenter_name }}/network/{{ my_vcenter_virtual_switch_name }}/{{ my_vcenter_port_segment_name }}') }}"

    - name: Look for MOID of VM called _temporary_rhelvm_do_not_delete
      register: my_vm
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
          - _temporary_rhelvm_do_not_delete

    - name: Print out infos on my_vm
      ansible.builtin.debug:
        var: my_vm
      when: debug | default('false') | bool

    - name: Collect information about a specific VM
      vmware.vmware_rest.vcenter_vm_info:
        vm: "{{ my_vm.value[0].vm }}"
      register: my_vm_info

    - name: Print out infos on my_vm_info
      ansible.builtin.debug:
        var: my_vm_info
      when: debug | default('false') | bool

    - name: Power on VM
      vmware.vmware_rest.vcenter_vm_power:
        state: start
        vm: "{{ my_vm.value[0].vm }}"

    - name: Wait for guest network interfaces information to be available
      vmware.vmware_rest.vcenter_vm_guest_networking_interfaces_info:
        vm: "{{ my_vm_info.id }}"
      register: my_vm_interfaceinfo
      retries: 60
      delay: 10 # seconds
      until:
        - my_vm_interfaceinfo.value[0] is defined

    - name: Print out infos on my_vm_interfaceinfo
      ansible.builtin.debug:
        var: my_vm_interfaceinfo
      when: debug | default('false') | bool

    - name: Extract ip address
      ansible.builtin.set_fact:
        # my_vm_ip: "{{ my_vm_interfaceinfo.value[0].ip.ip_addresses[1].ip_address }}"
        my_vm_ip: "{{ my_vm_interfaceinfo | community.general.json_query(ip_query) }}"
      vars:
        ip_query: value[0].ip.ip_addresses[?state=='PREFERRED'].ip_address

    - name: Print out ip address
      ansible.builtin.debug:
        var: my_vm_ip
      when: debug | default('false') | bool

    - name: Add Host to inventory
      ansible.builtin.add_host:
        name: "_temporary_rhelvm"
        ansible_host: "{{ my_vm_ip }}"
        # ansible_user:
        # ansible_password:
      when: awx_inventory_name is not defined

    - name: Add hosts to static inventory
      ansible.controller.host:
        # controller_host: "{{ lookup('ENV','CONTROLLER_HOST') }}"
        # controller_username: "{{ lookup('ENV','CONTROLLER_USERNAME') }}"
        # controller_password: "{{ lookup('ENV', 'CONTROLLER_PASSWORD') }}"
        validate_certs: false
        inventory: "{{ awx_inventory_name }}"
        name: "_temporary_rhelvm"
        enabled: true
        state: present
        variables:
          ansible_host: "{{ my_vm_ip }}"
      when: awx_inventory_name is defined

    - name: Wait for ssh to be ready
      ansible.builtin.wait_for:
        port: 22
        host: "{{ my_vm_ip }}"
        delay: 10 # seconds
        timeout: 600

    - name: Power off VM
      vmware.vmware_rest.vcenter_vm_power:
        state: stop
        vm: "{{ my_vm.value[0].vm }}"

    - name: List the cdrom devices on the guest
      vmware.vmware_rest.vcenter_vm_hardware_cdrom_info:
        vm: "{{ my_vm.value[0].vm }}"
      register: cdrom_guest

    - name: Detach CDROM from VM
      vmware.vmware_rest.vcenter_vm_hardware_cdrom:
        vm: "{{ my_vm.value[0].vm }}"
        cdrom: "{{ cdrom_guest.value[0] }}"
        state: absent

    - name: Create a content library based on a DataStore
      vmware.vmware_rest.content_locallibrary:
        name: "{{ my_content_library_name }}"
        description: automated
        publish_info:
          published: true
          authentication_method: NONE
        storage_backings:
          - datastore_id: "{{ lookup('vmware.vmware_rest.datastore_moid', '/{{ my_vcenter_datacenter_name }}/datastore/{{ my_vcenter_datastore_name }}') }}"
            type: DATASTORE
        state: present

    - name: List all Local Content Library
      register: all_content_libraries
      vmware.vmware_rest.content_locallibrary_info:

    - name: Filter out content library id
      ansible.builtin.set_fact:
        my_content_library: "{{ all_content_libraries.value | selectattr('name', 'equalto', my_content_library_name) }}"

    - name: Create a template from VM in the library
      vmware.vmware_rest.vcenter_vmtemplate_libraryitems:
        name: "{{ my_template_name }}"
        library: "{{ my_content_library[0].id }}"
        source_vm: "{{ my_vm.value[0].vm }}"
        placement:
          cluster: "{{ lookup('vmware.vmware_rest.cluster_moid', '/{{ my_vcenter_datacenter_name }}/host/{{ my_vcenter_cluster_name }}') }}"
          folder: "{{ lookup('vmware.vmware_rest.folder_moid', '/{{ my_vcenter_datacenter_name }}/vm/{{ my_vcenter_folder_name }}') }}"

    - name: Delete VM
      vmware.vmware_rest.vcenter_vm:
        vm: "{{ my_vm.value[0].vm }}"
        state: absent
