---
- name: Playbook to create a VMware vm from a custom template
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
  - name: ver parametros
    ansible.builtin.debug:
      msg: 'Nombre de máquina {{ item.name }} fichero de definiciones machines_def_{{ type }}.yml'
    loop: "{{ lookup('file', 'machines_def_vmware.yml') | from_yaml }}"
  
#  - name: Clone the template
#    community.vmware.vmware_guest:
#      hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
#      username: "{{ lookup('env', 'VMWARE_USER') }}"
#      password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
#      validate_certs: False
#      name: "{{ item.my_vcenter_vm_name }}"
#      template: "{{ item.my_template_name }}"
#      datacenter: "{{ item.my_vcenter_datacenter_name }}"
#      folder: "{{ item.my_vcenter_vm_parent_folder_name }}"
#      state: poweredon
#      cluster: "{{ item.my_vcenter_cluster_name }}"
#      wait_for_ip_address: yes
#    loop: "{{ lookup('file', 'machines_def_vmware.yml') | from_yaml }}"