---
- name: Delete all VM's in vCenter
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

    - name: Get all VM's in vCenter
      register: all_vms
      vmware.vmware_rest.vcenter_vm_info:

    - name: Power off all VM's
      loop: "{{ all_vms.value }}"
      vmware.vmware_rest.vcenter_vm_power:
        state: stop
        vm: "{{ item.vm }}"

    - name: Delete all VM's (this task fails for all the vCTL VM's)
      loop: "{{ all_vms.value }}"
      vmware.vmware_rest.vcenter_vm:
        vm: '{{ item.vm }}'
        state: absent
