---
- name: Playbook to create a VMware vm from a custom template
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

    - name: Get all Local Content Library
      vmware.vmware_rest.content_locallibrary_info:
      register: all_content_libraries

    - name: Filter our content library
      ansible.builtin.set_fact:
        my_content_library: "{{ all_content_libraries.value | selectattr('name', 'equalto', my_content_library_name) }}"

    - name: Get the list of items of the library
      register: lib_items
      vmware.vmware_rest.content_library_item_info:
        library_id: '{{ my_content_library[0].id }}'

    - name: Use the name to identify the item
      ansible.builtin.set_fact:
        my_template_item: "{{ lib_items.value | selectattr('name', 'equalto', my_template_name) | first }}"

    - name: Deploy a new VM based on the template
      loop: "{{ my_vms_from_template }}" 
      vmware.vmware_rest.vcenter_vmtemplate_libraryitems:
        session_timeout: 10000
        name: "{{ item.name }}"
        library: '{{ my_content_library[0].id }}'
        template_library_item: '{{ my_template_item.id }}'
        placement:
          cluster: "{{ lookup('vmware.vmware_rest.cluster_moid', '/{{ my_vcenter_datacenter_name }}/host/{{ my_vcenter_cluster_name }}') }}"
          # datastore: "{{ lookup('vmware.vmware_rest.datastore_moid', '/{{ my_vcenter_datacenter_name }}/datastore/{{ my_vcenter_datastore_name }}') }}"
          folder: "{{ lookup('vmware.vmware_rest.folder_moid', '/{{ my_vcenter_datacenter_name }}/vm/{{ my_vcenter_folder_name }}') }}"
        powered_on: true
        state: deploy
