---
- name: Install packages needed (genisoimage, mkisofs, syslinux, isomd5sum)
  ansible.builtin.dnf:
    name:
      - genisoimage
      - mkisofs
      - syslinux
      - isomd5sum
    state: present

- name: Create Windows custom iso
  when: my_os_type == "Windows"
  ansible.builtin.include_tasks:
    file: windows-iso.yml

- name: Create RHEL custom iso
  when: my_os_type == "RHEL"
  ansible.builtin.include_tasks:
    file: rhel-iso.yml

- name: Remove used packages (genisoimage, mkisofs, syslinux, isomd5sum)
  ansible.builtin.yum:
    name:
      - genisoimage#
      - mkisofs
      - syslinux
      - isomd5sum
    state: absent
